// Projeto-Calculadora-React/calculadora/src/main/Calculator.jsx
import React, { Component } from 'react' // Importando para o "Component".
import './Calculator.css' // Referenciando já o CSS.

import Button from '../components/Button'
import Display from '../components/Display'

const initialState = { // Aqui vai zerá o contador.
    displayValue: '0', // Diz o valor do Display
    clearDisplay: false, // Para limpar o Display
    operation: null,
    values: [0, 0], //
    current: 0
}

export default class Calculator extends Component {

    // Criado um clone do objeto e atribuido ao state.
    state = { ...initialState } // adicionando a contate para poder fazer a calculadora adicionar ou limpar

    constructor(props) { // função para da aos buttons funcionamento. a cada click.
        super(props)
        
        this.clearMemory = this.clearMemory.bind(this)
        this.setOperation = this.setOperation.bind(this)
        this.addDigit = this.addDigit.bind(this)
    }

    clearMemory() { // Função de limpar os numeros digitados
        this.setState({ ...initialState}) // Fazendo com que o contador seja limpo, caso seja apertando ele volta para o estado inicial.
    }


    // Toda essa função é para ativa as operações de SOMA, SUBTRAÇÃO, DIVISÃO, MULTIPLICAÇÃO.
    // 
    setOperation(operation) { // Função para setar os calculos para definir se é uma: SOMA, SUBTRAÇÃO, DIVISÃO, MULTIPLICAÇÃO.
        
        if(this.state.current === 0) { // Mexer em current para pegar segundo valor do vetor.
            this.setState({ operation, current: 1, clearDisplay: true }) // Quando recebe uma operação troca para o segundo elemento do vetor.
        } else {
            const equals = operation === '=' // Quando for clickando em -> ' = '
            const currentOperation = this.state.operation // Pegar operação corrente.

            const values = [...this.state.values]
            try {
                // Executa as operações com os dois indices do vetore armazena no indice 0.
                values[0] = eval (`${values[0]} ${currentOperation} ${values[1]}`)
                if (isNaN(values[0]) || !isFinite(values[0])) { // Faz com que pare que os numeros sejam infintos sendo digitados.
                    this.clearMemory()
                return
                }
            } catch (e) {
                values[0] = this.state.values[0]
            }
            values[1] = 0

            this.setState({
                displayValue: values[0], // Resultado da operação exibido no display.
                operation: equals ? null : operation, // Se for igual exibe resultado senão segue p/ próxima operação.
                current: equals ? 0 : 1,
                clearDisplay: !equals, // Se for diferente de equals não limpa display.
                values
            })
        }
    }

    // Toda a função faz com que inclua numero no display da calculadora.
    addDigit(n) { // Adiciona o digito quando clicka.
        if (n === '.' && this.state.displayValue.includes('.')) { // Impede que usuário digite um outro -> ponto '.' caso o display já possua '.'
            return
        }

        const clearDisplay = this.state.displayValue === '0' // Quando precisa limpar display
            || this.state.clearDisplay
        const currentValue = clearDisplay ? '' : this.state.displayValue // Se precisar limpar display o valor corrente assume vazio, caso contrário assume o valor do display
        const displayValue = currentValue + n
        this.setState({ displayValue, clearDisplay: false }) // Mudando o estado da aplicação que no caso é que quando for clickado o numero ele vai ser adicionado.
    
        if (n !== '.') {
            const i = this.state.current // Pega indice do elemento digitado.
            const newValue = parseFloat(displayValue) // Converte em Float.
            const values = [...this.state.values] // Clona em um novo array.
            values[i] = newValue
            this.setState({ values }) // Substitui novo array dentro de State
            console.log(values)
        }
    }

    render() {
        return (
            <div className="calculator"> {/* Para se Referencia class no REACT eles usam assim-> className */}
                <Display value={this.state.displayValue}/> {/*Mostra o valor que tem lá no displayValue.*/}
                <Button label="AC" click={this.clearMemory} triple/>
                <Button label="/" click={this.setOperation} operation/>
                <Button label="7" click={this.addDigit} />
                <Button label="8" click={this.addDigit} />
                <Button label="9" click={this.addDigit} />
                <Button label="*" click={this.setOperation} operation />
                <Button label="4" click={this.addDigit} />
                <Button label="5" click={this.addDigit} />
                <Button label="6" click={this.addDigit} />
                <Button label="-" click={this.setOperation} operation />
                <Button label="1" click={this.addDigit} />
                <Button label="2" click={this.addDigit} />
                <Button label="3" click={this.addDigit} />
                <Button label="+" click={this.setOperation} operation />
                <Button label="0" click={this.addDigit} double />
                <Button label="." click={this.addDigit}/>
                <Button label="=" click={this.setOperation} operation/>
            </div>
        )
    }
}




// constructor(props) {
//     super(props)
//     this.clearMemory = this.clearMemory.bind(this)
//     this.setOperation = this.setOperation.bind(this)
//     this.addDigit = this.addDigit.bind(this)
//     // This será resolvido para as funções
//     // Bind retorna um objeto/função

//     // ||
//     // Recebendo valores e passando para as funções 
//     // const addDigit = n => this.addDigit(n)
//     // const setOperation = op => this.setOperation(op)
// }

// Projeto-Calculadora-VueJS/calculator/src/main/Calculator.vue
<template>
    <div class="calculator">
        <Display :value="displayValue"/>
        <Button label="AC" triple @onClick="clearMemory"/>
        <Button label="/" operation @onClick="setOperation"/>
        <Button label="7" @onClick="addDigito"/>
        <Button label="8" @onClick="addDigito"/>
        <Button label="9" @onClick="addDigito"/>
        <Button label="*" operation @onClick="setOperation"/>
        <Button label="4" @onClick="addDigito"/>
        <Button label="5" @onClick="addDigito"/>
        <Button label="6" @onClick="addDigito"/>
        <Button label="-" operation @onClick="setOperation"/>
        <Button label="1" @onClick="addDigito"/>
        <Button label="2" @onClick="addDigito"/>
        <Button label="3" @onClick="addDigito"/>
        <Button label="+" operation @onClick="setOperation"/>
        <Button label="0" double @onClick="addDigito"/>
        <Button label="." @onClick="addDigito"/>
        <Button label="=" operation @onClick="setOperation"/>
    </div>
</template>

<script>
import Display from '../components/Display'
import Button from '../components/Button'
export default {
    data: function() {
        return { // Estado inicial
            displayValue: "0",
            clearDisplay: false,
            operation: null,
            values: [0, 0],
            current: 0 // Qual dos valores está sendo trabalho | Indice array values
        }
    },
    components: { Button, Display,},
    methods: { // Atribuindo estado inicial do objeto
        clearMemory() {
            Object.assign(this.$data, this.$options.data())
        },
        setOperation(operation) {
            // Quando usuário estiver informando primeiro valor
            if (this.current === 0 ) {
                this.operation = operation
                this.current = 1
                // Quando iniciar a digitar segundo valor | Após operação 
                this.clearDisplay = true
            } else {
                const equals = operation === "="
                const currentOperation = this.operation
                try {
                    this.values[0] = eval(
                        // Realiza operação passada anteriormente
                        `${this.values[0]} ${currentOperation} ${this.values[1]}`);
                        if (isNaN(this.values[0]) || !isFinite(this.values[0])) {
	                        this.clearMemory()
                            return
                        } // Para retira o Erro De NaN.
                } catch (e) {
                    this.$emit('onError', e)
                }
                this.values[1] = 0
                // Indice 1 do vetor zerado
                // Indice 0 do vetor recebe resultado da operação 
                this.displayValue = this.values[0]
                this.operation = equals ? null : operation
                // Se usuário selecionou "=", resultado passa para indice 0, senão vai para indice 1
                this.current = equals ? 0 : 1
                // Se operação for diferente de "=" limpa o display
                this.clearDisplay = !equals 
            }
        },
        addDigito(n) {
            if(n === "." && this.displayValue.includes(".")) {
                return
            }
            // Casos em que irá limpar o display
            const clearDisplay = this.displayValue === "0"
                || this.clearDisplay
            // currentValue recebe vazio se clearDisplay estiver setado, do contrário recebe o valor do display
            const currentValue = clearDisplay ? "" : this.displayValue
            // displayValue recebe currentValue com o digito passado
            const displayValue = currentValue + n
            // Tornando displayValue disponível para outras funções
            this.displayValue = displayValue
            this.clearDisplay = false
            // Alternativa
            // Indice do array recebe o valor no display
            this.values[this.current] = displayValue
            // if (n !== "." ) {
            //     // Coloca valor no devido indice do array
            //     const i = this.current
            //     // Define newValue para que se possa realizar a operação entre dois indices do array
            //     const newValue = parseFloat(displayValue)
            //     this.values[i] = newValue
            // }
        }
    }
}
</script>

<style>
.calculator {
    height: 320px;
    width: 235px;
    border-radius: 5px;
    overflow: hidden;
    display: grid;
    grid-template-columns: repeat(4, 25%);
    grid-template-rows: 1fr 48px 48px 48px 48px 48px;
}
</style>
